### PR TITLE
Design of "Get List"

### PR DESCRIPTION
**Pull request by Nilay2711**
So the question was how we provide the list to user....

I have came up with the solution to email them.....

Here I have added  Front End for that 

Also added a Snackbar Message On Clicking Send Button

Screenshot (154)

### CODE REVIEW

**Comment by krazykaushal** [comment]
First of all create an issue and wait for the maintainers to look into it. Second is I want two of the problems in this issue to be solved.

1. Don't remove the Sign in/ Sign Out feature.
2. Fix the navbar issue.
issue1

**Comment by Nilay2711** [comment]
Sorry Sir, I will look into the matter at once.

**Comment by Nilay2711** [comment]
Sir, I have committed the required changes.
Please have a look.

Also Sir again I am facing the same issue like last time....
 
 Hacktoberfest Website is again showing my Pull Request as "Project Not Participating".
 
 
image

**Comment by krazykaushal** [comment]
There are some conflicts in merging this to the main. So please update your repository with the main one and have a look into it and revert back. Also I am looking into the hacktoberfest issue so don't worry and let me know whether that gets resolved too or not.
Thanks

**Comment by Nilay2711** [comment]
Done Sir, 
Actually, As I downloaded the project yesterday and there was a new merge in last 20 hrs there was a conflict which I have solved keeping both Merges as one.

**Comment by krazykaushal** [comment]
So you did fixed the navbar issue but it seems like there are some more issues, So

- So previously on the main branch when you create the list it looks like below:
problem1

- But when I see your repository the created list looks like below:
problem

**So you have a look in this issue and try not to influence the other changes as well.
Thanks**

**Comment by Nilay2711** [comment]
Sir Here is the result.... I have fixed...

Also,
Have removed Contact Us Option...

I will work on Contact Us Option in soon in next issue....

Also have changed Share Option with Get List as their functions were same.

image

**Pull request merged**
