### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by harshmetkel24**
Hello maintainers,

I have added dark mode feature to this `repository`. I felt background image used, occupies most of the space in the UI, so there not too many components available to style according to theme. As Navbar is already dark in color.
I have tried to style rest all components according to dark theme, and also I make sure that there is smooth transition between colors on click.
If want me to make any changes, I will be happy to do that.
Happy Developing : )

### CODE REVIEW

**Comment by krazykaushal** [comment]
So what you can do is change the current navbar which suits well with the current UI after this #13 pull request is merged as there are some design changes in navbar in this pull request. And in dark mode you can change accordingly. Hope you have understood. In case of any queries feel free to ask.
Thanks.

**Comment by harshmetkel24** [comment]
> So what you can do is change the current navbar which suits well with the current UI after this #13 pull request is merged as there are some design changes in navbar in this pull request. And in dark mode you can change accordingly. Hope you have understood. In case of any queries feel free to ask.
> Thanks.

Okay I will look into it. And get back to you ASAP.

**Comment by harshmetkel24** [comment]
Hello @krazykaushal,
I have one doubt, that #13 is not merged yet. How can I get the updated code?
Is it that i have to clone @Nilay2711's repo or how can I do?
Thanks in Advance.

**Comment by krazykaushal** [comment]
#13 is merged now, update your code and you can start working on it.
Thanks

**Comment by harshmetkel24** [comment]
> #13 is merged now, update your code and you can start working on it.
> Thanks

Okay great, will get back to you ASAP.

**Comment by harshmetkel24** [comment]
Hello @krazykaushal,
First of all sorry for being so late to respond. Because was having some issues with my network today.
I have update my code to suit for dark-theme. Please review it and merge if everything goes well.
Thanks for this opportunity to contribute.

**Pull request merged**
