### PR TITLE
Sign-in-out

### PR DESCRIPTION
**Pull request by mananv1791**
**Added Things are as below.**

- Sign-in
- Sign-up

**Added three files**

- sign-up.html
- sign-up.css
- sign-in.html

### CODE REVIEW

**Comment by krazykaushal** [comment]
There are some conflicts in merging. Can you please look into it.
Thanks.

**Comment by mananv1791** [comment]
Yeah, It should work.

**Comment by krazykaushal** [comment]
@mananv1791 It says there are no more conflicts but one more problem comes up when I saw your repo. It looks like below:
problem2
Please have a look into it.
Thanks.

**Comment by mananv1791** [comment]
Hey there @krazykaushal 
I have fixed the homepage.


image

**Pull request merged**
